In [61]:
#Asset Return and Risk Analysis
import pandas as pd
pd.options.display.float_format = '{:.6f}'.format
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


# import Input data
data=pd.read_excel( r"C:\Users\koffi\OneDrive\Desktop\Project Study\Preject_Data.xlsx",format == "{:.2f}".format
)

In [62]:
#Data frame  for excel
data.head(10)

      Month  Asset A  Asset B  Asset C
0   January 0.040000 0.020000      −1%
1  February      −2% 0.010000 0.030000
2     March 0.050000 0.030000      −2%
3     April 0.010000      −1% 0.020000
4       May      −3%      −2% 0.040000
5      June 0.060000 0.020000      −1%

In [63]:
returns = pd.DataFrame({
    "Asset_A": [0.04, -0.02, 0.05, 0.01, -0.03, 0.06],
    "Asset_B": [0.02, 0.01, 0.03, -0.01, -0.02, 0.02],
    "Asset_C": [-0.01, 0.03, -0.02, 0.02, 0.04, -0.01],
}, index=["Jan", "Feb", "Mar", "Apr", "May", "Jun"])

In [64]:
returns

      Asset_A   Asset_B   Asset_C
Jan  0.040000  0.020000 -0.010000
Feb -0.020000  0.010000  0.030000
Mar  0.050000  0.030000 -0.020000
Apr  0.010000 -0.010000  0.020000
May -0.030000 -0.020000  0.040000
Jun  0.060000  0.020000 -0.010000

In [65]:
#  return mean by Asset
mean_returns=returns.mean()
print(mean_returns)
# return of high Asset mean
print("\nHighest Mean Return:", mean_returns.idxmax())

Asset_A   0.018333
Asset_B   0.008333
Asset_C   0.008333
dtype: float64

Highest Mean Return: Asset_A

In [ ]:
# Why is the mean important in financial analysis?
# The mean helps us answer three questions:
# 1. Performance: Which asset generated the highest average return?
# 2. Comparison: How do the average returns of different investments compare?
# 3. Portfolio management: What return might we use as an estimate when constructing a portfolio?

In [66]:
# Calculate sample variance
sample_variance = returns.var(ddof=1)
print(sample_variance)

Asset_A   0.001417
Asset_B   0.000377
Asset_C   0.000617
dtype: float64

In [ ]:
# 3. Why variance matters in quantitative finance
# Variance helps analysts evaluate how much uncertainty exists around an asset's average return.
# In practical terms:
# - Higher variance: Returns fluctuate more widely, indicating greater variability and uncertainty.
# - Lower variance: Returns are more concentrated around their mean, indicating greater historical stability.

In [72]:
# Calculate the Sampale Standard deviation
sample_std = returns.std(ddof=1)

print(sample_std)

Asset_A   0.037639
Asset_B   0.019408
Asset_C   0.024833
dtype: float64

In [73]:
# Return by volatity rank

volatility_ranking = returns.std(ddof=1).sort_values(
    ascending=False
)

print(volatility_ranking)

Asset_A   0.037639
Asset_C   0.024833
Asset_B   0.019408
dtype: float64

In [ ]:
# Ranking from highest to lowest volatility:
# 1. Asset A — Most volatile (3.76%)
# 2. Asset C — Moderate volatility (2.48%)
# 3. Asset B — Least volatile (1.94%)

In [81]:
# mean, variance, standard Deviation  recap
recp = pd.DataFrame({
    "Return Means": returns.mean(),
    "Return Variance": returns.var(ddof=1),
    "Return Volatility": returns.std(ddof=1).map("{:.2%}".format) #  map("{:.2%}".format) for the percentage. 
})

recp.index.name = "Asset"

print(recp.round(6))

         Return Means  Return Variance Return Volatility
Asset
Asset_A      0.018333         0.001417             3.76%
Asset_B      0.008333         0.000377             1.94%
Asset_C      0.008333         0.000617             2.48%

In [ ]:
#Analyze results:
# Asset A: Has the highest historical average return, but also the highest volatility. Its monthly returns fluctuate more substantially.
# Asset B: Has the lowest volatility, meaning its monthly returns were relatively more stable.
# Asset C: Has the same mean return as Asset B but higher volatility. Based only on these two statistics, Asset B has the more favorable risk-return profile.